### ISSUE TITLE
App crash on launch

### ISSUE THREAD

**Issue by vdkdamian** [parse-community/Parse-Swift#335]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description
When running on iOS or macOS, the app crashes. Happened after upgrading to 4.0.0.

### Steps to reproduce
Running the app with the newest version of the ParseSwift SDK

### Actual Outcome
App crash log:
```
You can't use ParseStorage without a backing store. An in-memory store is being used as a fallback.
ParseSwift/ParseStorage.swift:47: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
2022-01-27 19:51:41.577617+0100 Peral[32908:7709924] ParseSwift/ParseStorage.swift:47: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
```

### Expected Outcome
Normal behavior

### Environment

Client
- Parse Swift SDK version: `4.0.0`
- Xcode version: `13.2`
- Operating system (iOS, macOS, watchOS, etc.): `iOS, macOS`
- Operating system version: `iOS 15.2.1,  macOS 12.0.1`

Server
- Parse Server version: `4.5.0`
- Operating system: `Back4App`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS`

Database
- System (MongoDB or Postgres): `MongoDB `
- Database version: `Back4App`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `AWS`

### Logs
```
You can't use ParseStorage without a backing store. An in-memory store is being used as a fallback.
ParseSwift/ParseStorage.swift:47: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
2022-01-27 19:51:41.577617+0100 Peral[32908:7709924] ParseSwift/ParseStorage.swift:47: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
```

<img width="1840" alt="Schermafbeelding 2022-01-27 om 20 01 01" src="https://user-images.githubusercontent.com/44820440/151426042-6b598956-6e7b-4848-b414-d57e02cc7031.png">

**Comment by cbaker6** [comment]
Can you post how you are initializing the SDK?

**Comment by vdkdamian** [comment]
> Can you post how you are initializing the SDK?

```
ParseSwift.initialize(applicationId: "appId",
                              clientKey: "clientKey",
                              serverURL: URL(string: "serverURL")!)
```

**Comment by cbaker6** [comment]
My guess is you settings has changed with how you are using Keychain in your app. What happens when you use the Playgrounds?

The config there is: https://github.com/parse-community/Parse-Swift/blob/879055bc4665887dc1b04ce0a35ee2c828a8c857/ParseSwift.playground/Sources/Common.swift#L4-L19

The tests all use the standard config also, and I don't remember changing anything relating to the Storage. When you go back to 3.1.2 it works?

**Comment by cbaker6** [comment]
In addition, you had it working when you tested #332 right? Nothing was updated in the config. There was also very little code added to the SDK in general after that commit.

**Comment by vdkdamian** [comment]
> The tests all use the standard config also, and I don't remember changing anything relating to the Storage. When you go back to 3.1.2 it works?

No, I still have the crash. I do remember I needed to change some non optional variables to optionals for testing with your version of #332 of ParseObjects. But I don't think this has anything to do with that.

> In addition, you had it working when you tested #332 right? Nothing was updated in the config. There was also very little code added to the SDK in general after that commit.

Yes it worked back then. I don't know what I messed up, but it the crash clearly comes from ParseStorage.

**Comment by cbaker6** [comment]
Maybe you are attempting to use the SDK before it's initialized? Did you move code?

Below is where I configure the SDK:

SwiftUI based app: https://github.com/netreconlab/SnapCat/blob/3ca454850e073e4f8d3eb6b7a229353f0005a808/SnapCat/SnapCatApp.swift#L27-L29

AppDelegate: https://github.com/netreconlab/CareKitSample-ParseCareKit/blob/201894378f141323a888ec39564459f1c5ce44b4/OCKSample/AppDelegate.swift#L56-L62

**Comment by vdkdamian** [comment]
Yes, sorry indeed. I also added `CommandMenu` for macOS and needed some `@State` variables for this. I indeed used Parse before initializing completed.

**Comment by cbaker6** [comment]
How easy was the upgrade for you? Did the compiler provide most of the fixes needed? Anything special we should take note of to do when upgrading?

**Comment by vdkdamian** [comment]
> How easy was the upgrade for you? Did the compiler provide most of the fixes needed? Anything special we should take note of to do when upgrading?

Pretty easy, compiler indeed showed me what to change, but I oversaw the change where non-optional variables for ParseObject changed to must-be all optionals.

For the rest everything went flawless.

**Comment by cbaker6** [comment]
> but I oversaw the change where non-optional variables for ParseObject changed to must-be all optionals.

This makes sense since you've been using the SDK since older versions. I imagine the compiler told you to add `init()`? If you implemented `merge` for each of your objects, it will tell you which property isn't optional.

For new users of the SDK, it should be easy assuming they are following the Playground examples.
